### ISSUE TITLE
Regarding Berserk Jump

### ISSUE THREAD

**Issue by Paril** [skullernet/q2pro-rerelease-dll#1]
Hey - I worked on the Quake II Re-release. The Berserker jump was something I did and sadly I didn't catch that it didn't work properly in other tickrates. The gravity is too strong for 10hz since gravity is applied before movement - they just hit the ground immediately.

I devised a fix for it locally for a future patch which doesn't affect the 40hz gameplay but makes it work OK-ish on higher tickrates; it does cause him to "float" a bit on 10hz but it's better than not moving at all, heh.

```
static void berserk_high_gravity(edict_t *self)
{
	float gravity_scale = (800.f / level.gravity);

	if (self->velocity[2] < 0)
		self->gravity = 2.25f;
	else
		self->gravity = 5.25f;

	self->gravity /= (40.f / gi.tick_rate);
	self->gravity *= gravity_scale;
}
```

The other approach is to change `SV_Physics_Step` so that gravity is applied & reset to 1.0 after movement instead of before, but only when the Berserk is doing his jump. That seems to be closer to the real expected behavior, but it's more of a breaking change...

EDIT: actually, thinking more about this, a better approach would just be to give him one gravity's worth of clearance on the jump. This change works as well:

```
void berserk_jump_takeoff(edict_t *self)
{
	vec3_t forward;

	if (!self->enemy)
		return;

	// immediately turn to where we need to go
	float length = (self->s.origin - self->enemy->s.origin).length();
	float fwd_speed = length * 1.95f;
	vec3_t dir;
	PredictAim(self, self->enemy, self->s.origin, fwd_speed, false, 0.f, &dir, nullptr);
	self->s.angles[1] = vectoyaw(dir);
	AngleVectors(self->s.angles, forward, nullptr, nullptr);
	self->s.origin[2] += 1;
	self->velocity = forward * fwd_speed;
	self->velocity[2] = 400; // <-- reduce to 400 to counteract the new below block
	self->groundentity = nullptr;
	self->monsterinfo.aiflags |= AI_DUCKED;
	self->monsterinfo.attack_finished = level.time + 3_sec;
	self->touch = berserk_jump_touch;
	berserk_high_gravity(self);

        // apply 1 frames' worth of gravity to escape the floor
	self->gravity = -self->gravity;
	SV_AddGravity(self);
	self->gravity = -self->gravity;
}
```

**Comment by Paril** [comment]
The gravity manipulation was to have him pound down into the ground itself faster. If I increase the forwards velocity to reach them in the same amount of time, he just zips forwards with very little upwards velocity at all which was not only more unfair but also hard to read. I wanted the attack to have enough upwards velocity so he has sort of an 'arc' in the air, but without a lot of hang time.

The upcoming patch has a few more tweaks to his attack to make him more fair, but sadly this particular 10hz quirk isn't included in it.

If you have any other questions or reports about broken things let me know!

**Comment by skullernet** [comment]
Oh, I see. Regarding broken things I've noticed loop_volume/loop_attenuation entity_state_t fields were not saved when saving the game, don't think this is intended.

**Comment by Paril** [comment]
Oh that's a good catch! Thanks. I'll see if I can get it patched for our next patch cycle since its a very minimal impact bug.
